-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg8Mvt03HU14FVm4Vc
H1ThtNAcJ1Q9zSaqXtNqBLfhw0SgCgYIKoZIzj0DAQehRANCAASwlDLcNTOVgUgW
o9deF2o4ZJ9ssq3xVkHyLlzPmfeVekjeEXTWvMJFdqktWVCqylja1x06pc8NEhxQ
i2gBpptT
-----END PRIVATE KEY-----